version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Bleed
      MYSQL_ROOT_PASSWORD: Bleeddb2024*
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  myapp:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Bleed
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8001:8001"
volumes:
  db-data:
